input {
    kb_layout = us
    kb_variant = intl

    accel_profile = flat

    # TODO: touchpad
    # TODO: touchscreen
}

bindl = , switch:off:Lenovo Yoga Tablet Mode Control switch, exec, kill -USR2 $(cat /tmp/waybar-tablet-menu.pid)
bindl = , switch:off:Lenovo Yoga Tablet Mode Control switch, exec, kill -USR2 $(cat /tmp/waybar-tablet-close.pid)
bindl = , switch:off:Lenovo Yoga Tablet Mode Control switch, exec, gsettings set org.gnome.desktop.a11y.applications screen-keyboard-enabled false

bindl = , switch:on:Lenovo Yoga Tablet Mode Control switch, exec, kill -USR1 $(cat /tmp/waybar-tablet-menu.pid)
bindl = , switch:on:Lenovo Yoga Tablet Mode Control switch, exec, kill -USR1 $(cat /tmp/waybar-tablet-close.pid)
bindl = , switch:on:Lenovo Yoga Tablet Mode Control switch, exec, gsettings set org.gnome.desktop.a11y.applications screen-keyboard-enabled true

monitor=eDP-1,preferred,auto-right,1
monitor=,preferred,auto-left,1   # externals land to the left of the laptop
