# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Fixed workspaces
windowrule = match:class brave-browser, workspace 1 silent
windowrule = match:class kitty,         workspace 3
windowrule = match:class code,          workspace 4 silent

# Steam-specific
#windowrule = match:class steam, stay_focused on
#windowrule = match:class steam, min_size 1 1
windowrule = match:title Steam Big Picture Mode, fullscreen on

# Floats
windowrule = match:class org.gnome.Calculator,    float on
windowrule = match:class org.gnome.Nautilus,      float on
windowrule = match:class org.gnome.Calendar,      float on
windowrule = match:class blueberry.py,            float on
windowrule = match:class pavucontrol,             float on
windowrule = match:class explorer.exe,            float on
windowrule = match:class maplelegends.exe,        float on
windowrule = match:class org.gnome.SystemMonitor, float on
windowrule = match:class system-config-printer,   float on
windowrule = match:class nm-connection-editor,    float on
windowrule = match:class openrgb,                 float on
windowrule = match:class nsusbloader.NSLMain,     float on
windowrule = match:class steam,                   float on
windowrule = match:class tidal-hifi,              float on
windowrule = match:class ^.*iwgtk,                float on
windowrule = match:class xdg-desktop-portal-gtk,  float on
windowrule = match:class Xpra,                    float on
windowrule = match:class com.rtosta.zapzap,       float on

# Specific geometry windows
windowrule {
    name = pip
    match:title = Picture in picture
    float = on
    keep_aspect_ratio = on
    move = 1270 710
    pin = on
}

windowrule {
    name = Insync
    match:class = Insync
    float = on
    move = 1350 55
}

windowrule {
    name = foot
    match:class = foot
    float = on
    size = 780 340
    move = 1130 55
    pin = on
}
