# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Fixed workspaces
windowrulev2 = workspace 1 silent,class:(brave-browser)
windowrulev2 = workspace 3 silent,class:(kitty)
windowrulev2 = workspace 4 silent,class:(code)

# Floats
windowrulev2 = float, class:(org.gnome.Calculator)
windowrulev2 = float, class:(org.gnome.Nautilus)
windowrulev2 = float, class:(org.gnome.Calendar)
windowrulev2 = float, class:(blueberry.py)
windowrulev2 = float, class:(pavucontrol)
windowrulev2 = float, class:(org.gnome.SystemMonitor)
windowrulev2 = float, class:(system-config-printer)
windowrulev2 = float, class:(nm-connection-editor)
windowrulev2 = float, class:(io.github.lullabyX.sone)
windowrulev2 = float, class:^(.*iwgtk)
windowrulev2 = float, class:(xdg-desktop-portal-gtk)
windowrulev2 = float, class:(Xpra)
windowrulev2 = float, class:(com.rtosta.zapzap)

# Specific geometry windows
windowrulev2 = float, title:(Picture in picture)
windowrulev2 = move 2906 1130, title:(Picture in picture)
windowrulev2 = pin, title:(Picture in picture)
windowrulev2 = keepaspectratio, title:(Picture in picture)
