general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
	before_sleep_cmd = loginctl lock-session
}

# turn off keyboard backlight and RGB lights
listener {
    timeout = 30
    on-timeout = light -s sysfs/leds/platform::kbd_backlight -O && light -s sysfs/leds/platform::kbd_backlight -S 0
    on-resume = light -s sysfs/leds/platform::kbd_backlight -I
}

listener {
    timeout = 60
    on-timeout = light -O && light -T 0.1
    on-resume = light -I
}

listener {
    timeout = 120
    on-timeout = loginctl lock-session && hyprctl dispatch dpms off && systemctl stop --user waybar
	on-resume = hyprctl dispatch dpms on && systemctl start --user waybar
}

listener {
	timeout = 300
	on-timeout = systemctl hibernate
}
