general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
}

# turn off keyboard backlight and RGB lights
listener {
    timeout = 60
    on-timeout = openrgb -sp temp && openrgb -d 0 -m off && fg || true
    on-resume  = sleep 1 && openrgb -p temp              && fg || true
}

listener {
    timeout = 120
    on-timeout = hyprctl dispatch dpms off && systemctl stop  --user waybar
    on-resume  = hyprctl dispatch dpms on  && systemctl start --user waybar
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}
