preload = ~/Insync/angelodalzotto97@gmail.com/Google Drive/Imagens/Wallpapers/21-9/linuxretro.jpg
wallpaper = , ~/Insync/angelodalzotto97@gmail.com/Google Drive/Imagens/Wallpapers/21-9/linuxretro.jpg
