fps = [30,60,90,120]
global_prep_cmd = [{"do":"hyprctl output create headless SUNSHINE","undo":"hyprctl keyword monitor DP-3,3440x1440@144,auto,1,bitdepth,10"},{"do":"hyprctl keyword monitor DP-3,disable","undo":"hyprctl output remove SUNSHINE"}]
output_name = 0
resolutions = [
    1280x720,
    1920x1080,
    1920x1200,
    3840x2160
]
