# theme: Dark Modern

font=Source Code Pro:size=10

[colors]
cursor     = cccccc cccccc
foreground = cccccc
background = 181818

regular0 = 000000
regular1 = f85149
regular2 = 0dbc79
regular3 = 9e6a03
regular4 = 2472c8
regular5 = bc3fbc
regular6 = 11a8cd
regular7 = e5e5e5

bright0 = 181818
bright1 = f14c4c
bright2 = 23d18b
bright3 = f5f543
bright4 = 3b8eea
bright5 = d670d6
bright6 = 29b8db
bright7 = cccccc
